// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: usp/usp_record/usp-record-1-5.proto

package usp_record

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record_PayloadSecurity int32

const (
	Record_PLAINTEXT Record_PayloadSecurity = 0
	Record_TLS12     Record_PayloadSecurity = 1
)

// Enum value maps for Record_PayloadSecurity.
var (
	Record_PayloadSecurity_name = map[int32]string{
		0: "PLAINTEXT",
		1: "TLS12",
	}
	Record_PayloadSecurity_value = map[string]int32{
		"PLAINTEXT": 0,
		"TLS12":     1,
	}
)

func (x Record_PayloadSecurity) Enum() *Record_PayloadSecurity {
	p := new(Record_PayloadSecurity)
	*p = x
	return p
}

func (x Record_PayloadSecurity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Record_PayloadSecurity) Descriptor() protoreflect.EnumDescriptor {
	return file_usp_usp_record_usp_record_1_5_proto_enumTypes[0].Descriptor()
}

func (Record_PayloadSecurity) Type() protoreflect.EnumType {
	return &file_usp_usp_record_usp_record_1_5_proto_enumTypes[0]
}

func (x Record_PayloadSecurity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Record_PayloadSecurity.Descriptor instead.
func (Record_PayloadSecurity) EnumDescriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{0, 0}
}

type SessionContextRecord_PayloadSARState int32

const (
	SessionContextRecord_NONE      SessionContextRecord_PayloadSARState = 0
	SessionContextRecord_BEGIN     SessionContextRecord_PayloadSARState = 1
	SessionContextRecord_INPROCESS SessionContextRecord_PayloadSARState = 2
	SessionContextRecord_COMPLETE  SessionContextRecord_PayloadSARState = 3
)

// Enum value maps for SessionContextRecord_PayloadSARState.
var (
	SessionContextRecord_PayloadSARState_name = map[int32]string{
		0: "NONE",
		1: "BEGIN",
		2: "INPROCESS",
		3: "COMPLETE",
	}
	SessionContextRecord_PayloadSARState_value = map[string]int32{
		"NONE":      0,
		"BEGIN":     1,
		"INPROCESS": 2,
		"COMPLETE":  3,
	}
)

func (x SessionContextRecord_PayloadSARState) Enum() *SessionContextRecord_PayloadSARState {
	p := new(SessionContextRecord_PayloadSARState)
	*p = x
	return p
}

func (x SessionContextRecord_PayloadSARState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionContextRecord_PayloadSARState) Descriptor() protoreflect.EnumDescriptor {
	return file_usp_usp_record_usp_record_1_5_proto_enumTypes[1].Descriptor()
}

func (SessionContextRecord_PayloadSARState) Type() protoreflect.EnumType {
	return &file_usp_usp_record_usp_record_1_5_proto_enumTypes[1]
}

func (x SessionContextRecord_PayloadSARState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionContextRecord_PayloadSARState.Descriptor instead.
func (SessionContextRecord_PayloadSARState) EnumDescriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{2, 0}
}

type MQTTConnectRecord_MQTTVersion int32

const (
	MQTTConnectRecord_V3_1_1 MQTTConnectRecord_MQTTVersion = 0
	MQTTConnectRecord_V5     MQTTConnectRecord_MQTTVersion = 1
)

// Enum value maps for MQTTConnectRecord_MQTTVersion.
var (
	MQTTConnectRecord_MQTTVersion_name = map[int32]string{
		0: "V3_1_1",
		1: "V5",
	}
	MQTTConnectRecord_MQTTVersion_value = map[string]int32{
		"V3_1_1": 0,
		"V5":     1,
	}
)

func (x MQTTConnectRecord_MQTTVersion) Enum() *MQTTConnectRecord_MQTTVersion {
	p := new(MQTTConnectRecord_MQTTVersion)
	*p = x
	return p
}

func (x MQTTConnectRecord_MQTTVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MQTTConnectRecord_MQTTVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_usp_usp_record_usp_record_1_5_proto_enumTypes[2].Descriptor()
}

func (MQTTConnectRecord_MQTTVersion) Type() protoreflect.EnumType {
	return &file_usp_usp_record_usp_record_1_5_proto_enumTypes[2]
}

func (x MQTTConnectRecord_MQTTVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MQTTConnectRecord_MQTTVersion.Descriptor instead.
func (MQTTConnectRecord_MQTTVersion) EnumDescriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{4, 0}
}

type STOMPConnectRecord_STOMPVersion int32

const (
	STOMPConnectRecord_V1_2 STOMPConnectRecord_STOMPVersion = 0
)

// Enum value maps for STOMPConnectRecord_STOMPVersion.
var (
	STOMPConnectRecord_STOMPVersion_name = map[int32]string{
		0: "V1_2",
	}
	STOMPConnectRecord_STOMPVersion_value = map[string]int32{
		"V1_2": 0,
	}
)

func (x STOMPConnectRecord_STOMPVersion) Enum() *STOMPConnectRecord_STOMPVersion {
	p := new(STOMPConnectRecord_STOMPVersion)
	*p = x
	return p
}

func (x STOMPConnectRecord_STOMPVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STOMPConnectRecord_STOMPVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_usp_usp_record_usp_record_1_5_proto_enumTypes[3].Descriptor()
}

func (STOMPConnectRecord_STOMPVersion) Type() protoreflect.EnumType {
	return &file_usp_usp_record_usp_record_1_5_proto_enumTypes[3]
}

func (x STOMPConnectRecord_STOMPVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STOMPConnectRecord_STOMPVersion.Descriptor instead.
func (STOMPConnectRecord_STOMPVersion) EnumDescriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{5, 0}
}

type Record struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ToId            string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	FromId          string                 `protobuf:"bytes,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	OriginatorId    string                 `protobuf:"bytes,14,opt,name=originator_id,json=originatorId,proto3" json:"originator_id,omitempty"`
	DestinationId   string                 `protobuf:"bytes,15,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	PayloadSecurity Record_PayloadSecurity `protobuf:"varint,4,opt,name=payload_security,json=payloadSecurity,proto3,enum=usp_record.Record_PayloadSecurity" json:"payload_security,omitempty"`
	MacSignature    []byte                 `protobuf:"bytes,5,opt,name=mac_signature,json=macSignature,proto3" json:"mac_signature,omitempty"`
	SenderCert      []byte                 `protobuf:"bytes,6,opt,name=sender_cert,json=senderCert,proto3" json:"sender_cert,omitempty"`
	// Types that are valid to be assigned to RecordType:
	//
	//	*Record_NoSessionContext
	//	*Record_SessionContext
	//	*Record_WebsocketConnect
	//	*Record_MqttConnect
	//	*Record_StompConnect
	//	*Record_Disconnect
	//	*Record_UdsConnect
	RecordType    isRecord_RecordType `protobuf_oneof:"record_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Record) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Record) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Record) GetOriginatorId() string {
	if x != nil {
		return x.OriginatorId
	}
	return ""
}

func (x *Record) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *Record) GetPayloadSecurity() Record_PayloadSecurity {
	if x != nil {
		return x.PayloadSecurity
	}
	return Record_PLAINTEXT
}

func (x *Record) GetMacSignature() []byte {
	if x != nil {
		return x.MacSignature
	}
	return nil
}

func (x *Record) GetSenderCert() []byte {
	if x != nil {
		return x.SenderCert
	}
	return nil
}

func (x *Record) GetRecordType() isRecord_RecordType {
	if x != nil {
		return x.RecordType
	}
	return nil
}

func (x *Record) GetNoSessionContext() *NoSessionContextRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_NoSessionContext); ok {
			return x.NoSessionContext
		}
	}
	return nil
}

func (x *Record) GetSessionContext() *SessionContextRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_SessionContext); ok {
			return x.SessionContext
		}
	}
	return nil
}

func (x *Record) GetWebsocketConnect() *WebSocketConnectRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_WebsocketConnect); ok {
			return x.WebsocketConnect
		}
	}
	return nil
}

func (x *Record) GetMqttConnect() *MQTTConnectRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_MqttConnect); ok {
			return x.MqttConnect
		}
	}
	return nil
}

func (x *Record) GetStompConnect() *STOMPConnectRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_StompConnect); ok {
			return x.StompConnect
		}
	}
	return nil
}

func (x *Record) GetDisconnect() *DisconnectRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *Record) GetUdsConnect() *UDSConnectRecord {
	if x != nil {
		if x, ok := x.RecordType.(*Record_UdsConnect); ok {
			return x.UdsConnect
		}
	}
	return nil
}

type isRecord_RecordType interface {
	isRecord_RecordType()
}

type Record_NoSessionContext struct {
	NoSessionContext *NoSessionContextRecord `protobuf:"bytes,7,opt,name=no_session_context,json=noSessionContext,proto3,oneof"`
}

type Record_SessionContext struct {
	SessionContext *SessionContextRecord `protobuf:"bytes,8,opt,name=session_context,json=sessionContext,proto3,oneof"`
}

type Record_WebsocketConnect struct {
	WebsocketConnect *WebSocketConnectRecord `protobuf:"bytes,9,opt,name=websocket_connect,json=websocketConnect,proto3,oneof"`
}

type Record_MqttConnect struct {
	MqttConnect *MQTTConnectRecord `protobuf:"bytes,10,opt,name=mqtt_connect,json=mqttConnect,proto3,oneof"`
}

type Record_StompConnect struct {
	StompConnect *STOMPConnectRecord `protobuf:"bytes,11,opt,name=stomp_connect,json=stompConnect,proto3,oneof"`
}

type Record_Disconnect struct {
	Disconnect *DisconnectRecord `protobuf:"bytes,12,opt,name=disconnect,proto3,oneof"`
}

type Record_UdsConnect struct {
	UdsConnect *UDSConnectRecord `protobuf:"bytes,13,opt,name=uds_connect,json=udsConnect,proto3,oneof"`
}

func (*Record_NoSessionContext) isRecord_RecordType() {}

func (*Record_SessionContext) isRecord_RecordType() {}

func (*Record_WebsocketConnect) isRecord_RecordType() {}

func (*Record_MqttConnect) isRecord_RecordType() {}

func (*Record_StompConnect) isRecord_RecordType() {}

func (*Record_Disconnect) isRecord_RecordType() {}

func (*Record_UdsConnect) isRecord_RecordType() {}

type NoSessionContextRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoSessionContextRecord) Reset() {
	*x = NoSessionContextRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoSessionContextRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoSessionContextRecord) ProtoMessage() {}

func (x *NoSessionContextRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoSessionContextRecord.ProtoReflect.Descriptor instead.
func (*NoSessionContextRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{1}
}

func (x *NoSessionContextRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SessionContextRecord struct {
	state              protoimpl.MessageState               `protogen:"open.v1"`
	SessionId          uint64                               `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceId         uint64                               `protobuf:"varint,2,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	ExpectedId         uint64                               `protobuf:"varint,3,opt,name=expected_id,json=expectedId,proto3" json:"expected_id,omitempty"`
	RetransmitId       uint64                               `protobuf:"varint,4,opt,name=retransmit_id,json=retransmitId,proto3" json:"retransmit_id,omitempty"`
	PayloadSarState    SessionContextRecord_PayloadSARState `protobuf:"varint,5,opt,name=payload_sar_state,json=payloadSarState,proto3,enum=usp_record.SessionContextRecord_PayloadSARState" json:"payload_sar_state,omitempty"`
	PayloadrecSarState SessionContextRecord_PayloadSARState `protobuf:"varint,6,opt,name=payloadrec_sar_state,json=payloadrecSarState,proto3,enum=usp_record.SessionContextRecord_PayloadSARState" json:"payloadrec_sar_state,omitempty"`
	Payload            [][]byte                             `protobuf:"bytes,7,rep,name=payload,proto3" json:"payload,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionContextRecord) Reset() {
	*x = SessionContextRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContextRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContextRecord) ProtoMessage() {}

func (x *SessionContextRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContextRecord.ProtoReflect.Descriptor instead.
func (*SessionContextRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{2}
}

func (x *SessionContextRecord) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *SessionContextRecord) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *SessionContextRecord) GetExpectedId() uint64 {
	if x != nil {
		return x.ExpectedId
	}
	return 0
}

func (x *SessionContextRecord) GetRetransmitId() uint64 {
	if x != nil {
		return x.RetransmitId
	}
	return 0
}

func (x *SessionContextRecord) GetPayloadSarState() SessionContextRecord_PayloadSARState {
	if x != nil {
		return x.PayloadSarState
	}
	return SessionContextRecord_NONE
}

func (x *SessionContextRecord) GetPayloadrecSarState() SessionContextRecord_PayloadSARState {
	if x != nil {
		return x.PayloadrecSarState
	}
	return SessionContextRecord_NONE
}

func (x *SessionContextRecord) GetPayload() [][]byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WebSocketConnectRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketConnectRecord) Reset() {
	*x = WebSocketConnectRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketConnectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketConnectRecord) ProtoMessage() {}

func (x *WebSocketConnectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketConnectRecord.ProtoReflect.Descriptor instead.
func (*WebSocketConnectRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{3}
}

type MQTTConnectRecord struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Version         MQTTConnectRecord_MQTTVersion `protobuf:"varint,1,opt,name=version,proto3,enum=usp_record.MQTTConnectRecord_MQTTVersion" json:"version,omitempty"`
	SubscribedTopic string                        `protobuf:"bytes,2,opt,name=subscribed_topic,json=subscribedTopic,proto3" json:"subscribed_topic,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MQTTConnectRecord) Reset() {
	*x = MQTTConnectRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQTTConnectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQTTConnectRecord) ProtoMessage() {}

func (x *MQTTConnectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQTTConnectRecord.ProtoReflect.Descriptor instead.
func (*MQTTConnectRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{4}
}

func (x *MQTTConnectRecord) GetVersion() MQTTConnectRecord_MQTTVersion {
	if x != nil {
		return x.Version
	}
	return MQTTConnectRecord_V3_1_1
}

func (x *MQTTConnectRecord) GetSubscribedTopic() string {
	if x != nil {
		return x.SubscribedTopic
	}
	return ""
}

type STOMPConnectRecord struct {
	state                 protoimpl.MessageState          `protogen:"open.v1"`
	Version               STOMPConnectRecord_STOMPVersion `protobuf:"varint,1,opt,name=version,proto3,enum=usp_record.STOMPConnectRecord_STOMPVersion" json:"version,omitempty"`
	SubscribedDestination string                          `protobuf:"bytes,2,opt,name=subscribed_destination,json=subscribedDestination,proto3" json:"subscribed_destination,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *STOMPConnectRecord) Reset() {
	*x = STOMPConnectRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STOMPConnectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STOMPConnectRecord) ProtoMessage() {}

func (x *STOMPConnectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STOMPConnectRecord.ProtoReflect.Descriptor instead.
func (*STOMPConnectRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{5}
}

func (x *STOMPConnectRecord) GetVersion() STOMPConnectRecord_STOMPVersion {
	if x != nil {
		return x.Version
	}
	return STOMPConnectRecord_V1_2
}

func (x *STOMPConnectRecord) GetSubscribedDestination() string {
	if x != nil {
		return x.SubscribedDestination
	}
	return ""
}

type UDSConnectRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDSConnectRecord) Reset() {
	*x = UDSConnectRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDSConnectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDSConnectRecord) ProtoMessage() {}

func (x *UDSConnectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDSConnectRecord.ProtoReflect.Descriptor instead.
func (*UDSConnectRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{6}
}

type DisconnectRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	ReasonCode    uint32                 `protobuf:"fixed32,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRecord) Reset() {
	*x = DisconnectRecord{}
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRecord) ProtoMessage() {}

func (x *DisconnectRecord) ProtoReflect() protoreflect.Message {
	mi := &file_usp_usp_record_usp_record_1_5_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRecord.ProtoReflect.Descriptor instead.
func (*DisconnectRecord) Descriptor() ([]byte, []int) {
	return file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP(), []int{7}
}

func (x *DisconnectRecord) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DisconnectRecord) GetReasonCode() uint32 {
	if x != nil {
		return x.ReasonCode
	}
	return 0
}

var File_usp_usp_record_usp_record_1_5_proto protoreflect.FileDescriptor

const file_usp_usp_record_usp_record_1_5_proto_rawDesc = "" +
	"\n" +
	"#usp/usp_record/usp-record-1-5.proto\x12\n" +
	"usp_record\"\xed\x06\n" +
	"\x06Record\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\tR\x06fromId\x12#\n" +
	"\roriginator_id\x18\x0e \x01(\tR\foriginatorId\x12%\n" +
	"\x0edestination_id\x18\x0f \x01(\tR\rdestinationId\x12M\n" +
	"\x10payload_security\x18\x04 \x01(\x0e2\".usp_record.Record.PayloadSecurityR\x0fpayloadSecurity\x12#\n" +
	"\rmac_signature\x18\x05 \x01(\fR\fmacSignature\x12\x1f\n" +
	"\vsender_cert\x18\x06 \x01(\fR\n" +
	"senderCert\x12R\n" +
	"\x12no_session_context\x18\a \x01(\v2\".usp_record.NoSessionContextRecordH\x00R\x10noSessionContext\x12K\n" +
	"\x0fsession_context\x18\b \x01(\v2 .usp_record.SessionContextRecordH\x00R\x0esessionContext\x12Q\n" +
	"\x11websocket_connect\x18\t \x01(\v2\".usp_record.WebSocketConnectRecordH\x00R\x10websocketConnect\x12B\n" +
	"\fmqtt_connect\x18\n" +
	" \x01(\v2\x1d.usp_record.MQTTConnectRecordH\x00R\vmqttConnect\x12E\n" +
	"\rstomp_connect\x18\v \x01(\v2\x1e.usp_record.STOMPConnectRecordH\x00R\fstompConnect\x12>\n" +
	"\n" +
	"disconnect\x18\f \x01(\v2\x1c.usp_record.DisconnectRecordH\x00R\n" +
	"disconnect\x12?\n" +
	"\vuds_connect\x18\r \x01(\v2\x1c.usp_record.UDSConnectRecordH\x00R\n" +
	"udsConnect\"+\n" +
	"\x0fPayloadSecurity\x12\r\n" +
	"\tPLAINTEXT\x10\x00\x12\t\n" +
	"\x05TLS12\x10\x01B\r\n" +
	"\vrecord_type\"2\n" +
	"\x16NoSessionContextRecord\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xbd\x03\n" +
	"\x14SessionContextRecord\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x12\x1f\n" +
	"\vsequence_id\x18\x02 \x01(\x04R\n" +
	"sequenceId\x12\x1f\n" +
	"\vexpected_id\x18\x03 \x01(\x04R\n" +
	"expectedId\x12#\n" +
	"\rretransmit_id\x18\x04 \x01(\x04R\fretransmitId\x12\\\n" +
	"\x11payload_sar_state\x18\x05 \x01(\x0e20.usp_record.SessionContextRecord.PayloadSARStateR\x0fpayloadSarState\x12b\n" +
	"\x14payloadrec_sar_state\x18\x06 \x01(\x0e20.usp_record.SessionContextRecord.PayloadSARStateR\x12payloadrecSarState\x12\x18\n" +
	"\apayload\x18\a \x03(\fR\apayload\"C\n" +
	"\x0fPayloadSARState\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05BEGIN\x10\x01\x12\r\n" +
	"\tINPROCESS\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\"\x18\n" +
	"\x16WebSocketConnectRecord\"\xa6\x01\n" +
	"\x11MQTTConnectRecord\x12C\n" +
	"\aversion\x18\x01 \x01(\x0e2).usp_record.MQTTConnectRecord.MQTTVersionR\aversion\x12)\n" +
	"\x10subscribed_topic\x18\x02 \x01(\tR\x0fsubscribedTopic\"!\n" +
	"\vMQTTVersion\x12\n" +
	"\n" +
	"\x06V3_1_1\x10\x00\x12\x06\n" +
	"\x02V5\x10\x01\"\xac\x01\n" +
	"\x12STOMPConnectRecord\x12E\n" +
	"\aversion\x18\x01 \x01(\x0e2+.usp_record.STOMPConnectRecord.STOMPVersionR\aversion\x125\n" +
	"\x16subscribed_destination\x18\x02 \x01(\tR\x15subscribedDestination\"\x18\n" +
	"\fSTOMPVersion\x12\b\n" +
	"\x04V1_2\x10\x00\"\x12\n" +
	"\x10UDSConnectRecord\"K\n" +
	"\x10DisconnectRecord\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\aR\n" +
	"reasonCodeB#Z!conn-conductor/pkg/usp/usp_recordb\x06proto3"

var (
	file_usp_usp_record_usp_record_1_5_proto_rawDescOnce sync.Once
	file_usp_usp_record_usp_record_1_5_proto_rawDescData []byte
)

func file_usp_usp_record_usp_record_1_5_proto_rawDescGZIP() []byte {
	file_usp_usp_record_usp_record_1_5_proto_rawDescOnce.Do(func() {
		file_usp_usp_record_usp_record_1_5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usp_usp_record_usp_record_1_5_proto_rawDesc), len(file_usp_usp_record_usp_record_1_5_proto_rawDesc)))
	})
	return file_usp_usp_record_usp_record_1_5_proto_rawDescData
}

var file_usp_usp_record_usp_record_1_5_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_usp_usp_record_usp_record_1_5_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_usp_usp_record_usp_record_1_5_proto_goTypes = []any{
	(Record_PayloadSecurity)(0),               // 0: usp_record.Record.PayloadSecurity
	(SessionContextRecord_PayloadSARState)(0), // 1: usp_record.SessionContextRecord.PayloadSARState
	(MQTTConnectRecord_MQTTVersion)(0),        // 2: usp_record.MQTTConnectRecord.MQTTVersion
	(STOMPConnectRecord_STOMPVersion)(0),      // 3: usp_record.STOMPConnectRecord.STOMPVersion
	(*Record)(nil),                            // 4: usp_record.Record
	(*NoSessionContextRecord)(nil),            // 5: usp_record.NoSessionContextRecord
	(*SessionContextRecord)(nil),              // 6: usp_record.SessionContextRecord
	(*WebSocketConnectRecord)(nil),            // 7: usp_record.WebSocketConnectRecord
	(*MQTTConnectRecord)(nil),                 // 8: usp_record.MQTTConnectRecord
	(*STOMPConnectRecord)(nil),                // 9: usp_record.STOMPConnectRecord
	(*UDSConnectRecord)(nil),                  // 10: usp_record.UDSConnectRecord
	(*DisconnectRecord)(nil),                  // 11: usp_record.DisconnectRecord
}
var file_usp_usp_record_usp_record_1_5_proto_depIdxs = []int32{
	0,  // 0: usp_record.Record.payload_security:type_name -> usp_record.Record.PayloadSecurity
	5,  // 1: usp_record.Record.no_session_context:type_name -> usp_record.NoSessionContextRecord
	6,  // 2: usp_record.Record.session_context:type_name -> usp_record.SessionContextRecord
	7,  // 3: usp_record.Record.websocket_connect:type_name -> usp_record.WebSocketConnectRecord
	8,  // 4: usp_record.Record.mqtt_connect:type_name -> usp_record.MQTTConnectRecord
	9,  // 5: usp_record.Record.stomp_connect:type_name -> usp_record.STOMPConnectRecord
	11, // 6: usp_record.Record.disconnect:type_name -> usp_record.DisconnectRecord
	10, // 7: usp_record.Record.uds_connect:type_name -> usp_record.UDSConnectRecord
	1,  // 8: usp_record.SessionContextRecord.payload_sar_state:type_name -> usp_record.SessionContextRecord.PayloadSARState
	1,  // 9: usp_record.SessionContextRecord.payloadrec_sar_state:type_name -> usp_record.SessionContextRecord.PayloadSARState
	2,  // 10: usp_record.MQTTConnectRecord.version:type_name -> usp_record.MQTTConnectRecord.MQTTVersion
	3,  // 11: usp_record.STOMPConnectRecord.version:type_name -> usp_record.STOMPConnectRecord.STOMPVersion
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_usp_usp_record_usp_record_1_5_proto_init() }
func file_usp_usp_record_usp_record_1_5_proto_init() {
	if File_usp_usp_record_usp_record_1_5_proto != nil {
		return
	}
	file_usp_usp_record_usp_record_1_5_proto_msgTypes[0].OneofWrappers = []any{
		(*Record_NoSessionContext)(nil),
		(*Record_SessionContext)(nil),
		(*Record_WebsocketConnect)(nil),
		(*Record_MqttConnect)(nil),
		(*Record_StompConnect)(nil),
		(*Record_Disconnect)(nil),
		(*Record_UdsConnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usp_usp_record_usp_record_1_5_proto_rawDesc), len(file_usp_usp_record_usp_record_1_5_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usp_usp_record_usp_record_1_5_proto_goTypes,
		DependencyIndexes: file_usp_usp_record_usp_record_1_5_proto_depIdxs,
		EnumInfos:         file_usp_usp_record_usp_record_1_5_proto_enumTypes,
		MessageInfos:      file_usp_usp_record_usp_record_1_5_proto_msgTypes,
	}.Build()
	File_usp_usp_record_usp_record_1_5_proto = out.File
	file_usp_usp_record_usp_record_1_5_proto_goTypes = nil
	file_usp_usp_record_usp_record_1_5_proto_depIdxs = nil
}
